# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build_node_10:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run test:circleci

  build_node_9:
    docker:
      - image: circleci/node:9
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run test:circleci

  build_node_8:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run test:circleci

  build_node_6:
    docker:
      - image: circleci/node:6
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run test:circleci

workflows:
  version: 2
  run_test:
    jobs:
      - build_node_10
      - build_node_9
      - build_node_8
      - build_node_6
