# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build_node_12:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm ci
      - run: npm run test:lint
      - run: npm run test:unit
      - run: npm run test:system

  build_node_11:
    docker:
      - image: circleci/node:11
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm ci
      - run: npm run test:lint
      - run: npm run test:unit
      - run: npm run test:system

  build_node_10:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm ci
      - run: npm run test:lint
      - run: npm run test:unit
      - run: npm run test:system

  build_node_9:
    docker:
      - image: circleci/node:9
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run test:lint
      - run: npm run test:unit
      - run: npm run test:system

  build_node_8:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm ci
      - run: npm run test:lint
      - run: npm run test:unit
      - run: npm run test:system

workflows:
  version: 2
  run_test:
    jobs:
      - build_node_12:
          filters:
            tags:
              only: /^v.*/
      - build_node_11:
          filters:
            tags:
              only: /^v.*/
      - build_node_10:
          filters:
            tags:
              only: /^v.*/
      - build_node_9:
          filters:
            tags:
              only: /^v.*/
      - build_node_8:
          filters:
            tags:
              only: /^v.*/
  nightly:
    triggers:
      - schedule:
          cron: "0 14 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build_node_12
      - build_node_11
      - build_node_10
      - build_node_9
      - build_node_8
